name: FTP Deploy

on:
  push:
    branches:
      - main  # deploy on push to main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }}  # use ftps
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./        # folder to upload
          server-dir: /public_html/  # destination folder on your server
          passive: true        # Passive mode (recommended)
          dry-run: false       # change to true if you want to test first
